export const randomPrompts = [
  "rocket ship",
  "dolphins",
  "shooting star",
  "old lighthouse",
  "mountain cabin",
  "hot air balloon",
  "vintage motorcycle",
  "peacock feathers",
  "thunderstorm",
  "cherry blossoms",
  "owl in moonlight",
  "crystal cave",
  "grand piano",
  "sunflower field",
  "polar bear",
  "ancient ruins",
  "steaming coffee",
  "violin",
  "windmill",
  "jellyfish",
  "autumn leaves",
  "typewriter",
  "hummingbird",
  "castle tower",
  "coral reef",
  "bonsai tree",
  "compass",
  "whale breaching",
  "candle flame",
  "spiral staircase",
  "fox in snow",
  "gramophone",
  "dragonfly",
  "cathedral",
  "tiger",
  "hourglass",
  "tulip garden",
  "barn owl",
  "pocket watch",
  "northern lights",
  "seahorse",
  "paper crane",
  "vintage camera",
  "full moon",
  "elephants",
  "lighthouse beam",
  "fern leaves",
  "old bookshop",
  "flamingo",
  "grandfather clock",
  "wolf howling",
  "dandelion seeds",
  "train station",
  "heron",
  "ship in bottle",
  "butterfly",
  "stone bridge",
  "snowy owl",
  "spinning top",
  "japanese garden",
  "octopus",
  "telescope",
  "redwood forest",
  "swan",
  "antique key",
  "desert cactus",
  "lantern",
  "koi fish",
  "sailboat",
  "spider web",
  "eagle soaring",
  "piano keys",
  "tropical waterfall",
  "raven",
  "sundial",
  "mushrooms",
  "old mill",
  "starfish",
  "feather",
  "canyon sunset",
  "tortoise",
  "church bells",
  "bamboo forest",
  "manta ray",
  "rustic fence",
  "iris flower",
  "moose",
  "globe",
  "sea turtle",
  "harvest moon",
  "kingfisher",
  "crystal ball",
  "mountain goat",
  "lotus flower",
  "ship wheel",
  "fireflies",
  "arctic fox",
  "weathervane",
  "pelican",
  "wishing well",
  "giraffe",
  "street lamp",
  "seashell",
  "wine glass",
  "penguins",
  "covered bridge",
  "maple leaf",
  "saxophone",
  "parrot",
  "stone tower",
  "lily pad",
  "accordion",
  "zebra",
  "rope swing",
  "orchid",
  "trumpet",
  "leopard",
  "wooden dock",
  "poppy field",
  "clarinet",
  "cheetah",
  "garden gate",
  "daffodils",
  "cello",
  "gorilla",
  "brick wall",
  "magnolia",
  "flute",
  "orangutan",
  "iron fence",
  "hibiscus",
  "harp",
  "baboon",
  "stone wall",
  "carnation",
  "drums",
  "lemur",
  "picket fence",
  "peony",
  "guitar",
  "sloth",
  "wooden gate",
  "dahlia",
  "banjo",
  "koala",
  "hedge maze",
  "marigold",
  "ukulele",
  "kangaroo",
  "trellis",
  "zinnia",
  "mandolin",
  "wombat",
  "arbor",
  "chrysanthemum",
  "harmonica",
  "platypus",
  "pergola",
  "lilac",
  "bagpipes",
  "echidna",
  "gazebo",
  "jasmine",
  "fiddle",
  "tasmanian devil",
  "fountain",
  "lavender",
  "bass guitar",
  "dingo",
  "birdbath",
  "hydrangea",
  "keyboard",
  "wallaby",
  "sundial garden",
  "azalea",
  "xylophone",
  "quokka",
  "garden bench",
  "camellia",
  "tambourine",
  "capybara",
  "stone path",
  "wisteria",
  "maracas",
  "chinchilla",
  "cobblestone",
  "bleeding heart",
  "triangle",
  "ferret",
  "gravel path",
  "foxglove",
  "cymbals",
  "hedgehog",
  "stepping stones",
  "snapdragon",
  "gong",
  "porcupine",
  "mossy rocks",
  "hollyhock",
  "chimes",
  "armadillo",
  "river stones",
  "delphinium",
  "bells",
  "pangolin",
  "pebble beach",
  "sweet pea",
  "cowbell",
  "anteater",
  "sandy beach",
  "morning glory",
  "castanets",
  "aardvark",
  "rocky shore",
  "honeysuckle",
  "bongos",
  "meerkat",
  "tide pool",
  "clematis",
  "conga",
  "mongoose",
  "driftwood",
  "passionflower",
  "djembe",
  "badger",
  "seaweed",
  "bird of paradise",
  "steel drum",
  "raccoon",
  "kelp",
  "protea",
  "pan flute",
  "opossum",
  "barnacles",
  "anthurium",
  "ocarina",
  "skunk",
  "coral",
  "ginger flower",
  "recorder",
  "beaver",
  "anemone",
  "heliconia",
  "piccolo",
  "otter",
  "sea fan",
  "plumeria",
  "oboe",
  "mink",
  "sponge",
  "frangipani",
  "bassoon",
  "weasel",
  "urchin",
  "gardenia",
  "english horn",
  "stoat",
  "sand dollar",
  "tuberose",
  "french horn",
  "ermine",
  "conch",
  "stephanotis",
  "tuba",
  "wolverine",
  "nautilus",
  "lisianthus",
  "sousaphone",
  "fisher",
  "abalone",
  "ranunculus",
  "euphonium",
  "marten",
  "cowrie",
  "anemone flower",
  "cornet",
  "sable",
  "murex",
  "stock flower",
  "flugelhorn",
  "civet",
  "whelk",
  "statice",
  "bugle",
  "genet",
  "periwinkle shell",
  "aster",
  "alphorn",
  "binturong",
  "limpet",
  "cosmos",
  "didgeridoo",
  "kinkajou",
  "scallop",
  "black eyed susan",
  "sitar",
  "coati",
  "clam",
  "coneflower",
  "tabla",
  "cacomistle",
  "oyster",
  "cornflower",
  "tanpura",
  "ringtail",
  "mussel",
  "bachelor button",
  "sarod",
  "olingo",
  "cockle",
  "blanket flower",
  "veena",
  "tayra",
  "razor clam",
  "coreopsis",
  "santoor",
  "grison",
  "geoduck",
  "tickseed",
  "sarangi",
  "zorilla",
  "ark shell",
  "california poppy",
  "dilruba",
  "linsang",
  "pen shell",
  "iceland poppy",
  "esraj",
  "fossa",
  "angel wing",
  "welsh poppy",
  "rebab",
  "tenrec",
  "jingle shell",
  "oriental poppy",
  "erhu",
  "moonrat",
  "kitten paw",
  "matilija poppy",
  "pipa",
  "tree shrew",
  "lion paw",
  "himalayan poppy",
  "guzheng",
  "colugo",
  "turkey wing",
  "arctic poppy",
  "yangqin",
  "tarsier",
  "blood ark",
  "prickly poppy",
  "ruan",
  "slow loris",
  "cross barred venus",
  "sea poppy",
  "zhongruan",
  "galago",
  "sunray venus",
  "plume poppy",
  "liuqin",
  "potto",
  "lightning whelk",
  "wood poppy",
  "sanxian",
  "angwantibo",
  "fig shell",
  "horned poppy",
  "konghou",
  "aye aye",
  "tulip shell",
  "corn poppy",
  "sheng",
  "indri",
  "olive shell",
  "shirley poppy",
  "suona",
  "sifaka",
  "cone shell",
  "flanders poppy",
  "dizi",
  "sportive lemur",
  "harp shell",
  "breadseed poppy",
  "xiao",
  "mouse lemur",
  "mitre shell",
  "opium poppy",
  "bawu",
  "dwarf lemur",
  "volute",
  "wild rose",
  "hulusi",
  "fork marked lemur",
  "margin shell",
  "dog rose",
  "koudi",
  "woolly lemur",
  "bubble shell",
  "prairie rose",
  "xun",
  "bamboo lemur",
  "moon shell",
  "climbing rose",
  "paiban",
  "ruffed lemur",
  "ear shell",
  "shrub rose",
  "muyu",
  "crowned lemur",
  "top shell",
  "tea rose",
  "bangzi",
  "ring tailed lemur",
  "turban shell",
  "moss rose",
  "ban",
  "red lemur",
  "star shell",
  "musk rose",
  "pai",
  "black lemur",
  "sun shell",
  "china rose",
  "bo",
  "blue eyed lemur",
  "spider shell",
  "cabbage rose",
  "luo",
  "mongoose lemur",
  "pelican foot",
  "damask rose",
  "dagu",
  "crowned sifaka",
  "carrier shell",
  "gallica rose",
  "paigu",
  "verreaux sifaka",
  "slit shell",
  "bourbon rose",
  "tanggu",
  "coquerel sifaka",
  "keyhole limpet",
  "noisette rose",
  "bianzhong",
  "diademed sifaka",
  "chinese hat",
  "portland rose",
  "fangxiang",
  "silky sifaka",
  "slipper shell",
  "hybrid tea",
  "chime bells",
  "golden sifaka",
  "cup and saucer",
  "floribunda",
  "stone chimes",
  "tattersall sifaka",
  "worm shell",
  "grandiflora",
  "jade chimes",
  "milne edwards sifaka",
  "tusk shell",
  "polyantha",
  "tiger bells",
  "woolly spider monkey",
  "tooth shell",
  "miniature rose",
  "elephant bells",
  "muriqui",
  "paper nautilus",
  "ground cover rose",
  "temple bells",
  "howler monkey",
  "violet snail",
  "rambler rose",
  "wind bells",
  "spider monkey",
  "sea butterfly",
  "pillar rose",
  "rain bells",
  "squirrel monkey",
  "sea angel",
  "standard rose",
  "snow bells",
  "capuchin",
  "blue dragon",
  "weeping rose",
  "cloud bells",
  "saki",
  "sea slug",
  "cascade rose",
  "moon bells",
  "uakari",
  "nudibranch",
  "patio rose",
  "star bells",
  "titi monkey",
  "spanish dancer",
  "tree rose",
  "sun bells",
  "night monkey",
  "lettuce slug",
  "rose bush",
  "dream bells",
  "woolly monkey",
  "sacoglossan",
  "rose garden",
  "fairy bells",
  "tamarin",
  "sea hare",
  "rose arbor",
  "coral bells",
  "marmoset",
  "sea lemon",
  "rose trellis",
  "crystal bells",
  "pygmy marmoset",
  "dorid",
  "rose arch",
  "silver bells",
  "golden lion tamarin",
  "aeolid",
  "rose pergola",
  "golden bells",
  "emperor tamarin",
  "dendronotid",
  "rose bower",
  "brass bells",
  "cotton top tamarin",
  "arminid",
  "rose walk",
  "bronze bells",
  "saddleback tamarin",
  "tritoniid",
  "rose path",
  "copper bells",
  "white lipped tamarin",
  "chromodorid",
  "rose lane",
  "iron bells",
  "black mantled tamarin",
  "phyllidiid",
  "rose hedge",
  "porcelain bells",
  "moustached tamarin",
  "hexabranchid",
  "rose border",
  "ceramic bells",
  "red handed tamarin",
  "polycerid",
  "rose bed",
  "glass bells",
  "pied tamarin",
  "goniodorid",
  "rose plot",
  "wooden bells",
  "geoffroys tamarin",
  "onchidorid",
  "rose patch",
  "bamboo bells",
  "graells tamarin",
  "gymnodorid",
  "sunset",
  "sunrise",
  "rainbow",
  "thundercloud",
  "snowstorm",
  "sandstorm",
  "tornado",
  "hurricane",
  "blizzard",
  "hailstorm",
  "monsoon",
  "fog bank",
  "morning mist",
  "evening dew",
  "frost patterns",
  "icicles",
  "snowflakes",
  "raindrops",
  "lightning bolt",
  "thunder",
  "windstorm",
  "dust devil",
  "waterspout",
  "fire whirl",
  "sun shower",
  "double rainbow",
  "moonbow",
  "sun halo",
  "moon halo",
  "sun dogs",
  "light pillars",
  "mammatus clouds",
  "lenticular clouds",
  "cumulonimbus",
  "cirrus clouds",
  "stratus clouds",
  "altocumulus",
  "nimbostratus",
  "shelf cloud",
  "wall cloud",
  "funnel cloud",
  "red sky",
  "pink sky",
  "orange sky",
  "purple sky",
  "golden sky",
  "blue sky",
  "gray sky",
  "starry sky",
  "milky way",
  "meteor",
  "comet",
  "asteroid",
  "satellite",
  "space station",
  "planets",
  "jupiter",
  "saturn rings",
  "mars",
  "venus",
  "mercury",
  "neptune",
  "uranus",
  "pluto",
  "crescent moon",
  "half moon",
  "gibbous moon",
  "blood moon",
  "supermoon",
  "blue moon",
  "solar eclipse",
  "lunar eclipse",
  "constellation",
  "orion",
  "big dipper",
  "north star",
  "andromeda",
  "milky way center",
  "nebula",
  "supernova",
  "black hole",
  "pulsar",
  "quasar",
  "galaxy",
  "spiral galaxy",
  "star cluster",
  "globular cluster",
  "red giant",
  "white dwarf",
  "brown dwarf",
  "binary stars",
  "alien planet",
  "space shuttle",
  "lunar lander",
  "mars rover",
  "space telescope",
  "satellite dish",
  "radio telescope",
  "observatory dome",
  "astronaut",
  "space walk",
  "earth from space",
  "moon surface",
  "mars landscape",
  "rings of saturn",
  "jupiters moons",
  "asteroid belt",
  "kuiper belt",
  "oort cloud",
  "solar flare",
  "corona",
  "sunspot",
  "aurora",
  "northern lights",
  "southern lights",
  "zodiacal light",
  "gegenschein",
  "airglow",
  "noctilucent clouds",
  "green flash",
  "red flash",
  "crepuscular rays",
  "anticrepuscular rays",
  "glory",
  "brocken specter",
  "fogbow",
  "fire rainbow",
  "circumhorizontal arc",
  "circumzenithal arc",
  "parhelion",
  "anthelion",
  "parhelic circle",
  "diamond",
  "emerald",
  "ruby",
  "sapphire",
  "amethyst",
  "topaz",
  "opal",
  "pearl",
  "jade",
  "turquoise",
  "garnet",
  "peridot",
  "aquamarine",
  "citrine",
  "moonstone",
  "onyx",
  "obsidian",
  "malachite",
  "lapis lazuli",
  "tigers eye",
  "rose quartz",
  "smoky quartz",
  "clear quartz",
  "bloodstone",
  "carnelian",
  "jasper",
  "agate",
  "chalcedony",
  "alexandrite",
  "tanzanite",
  "zircon",
  "spinel",
  "tourmaline",
  "kunzite",
  "morganite",
  "tsavorite",
  "chrysoberyl",
  "labradorite",
  "sunstone",
  "amazonite",
  "rhodonite",
  "sodalite",
  "aventurine",
  "fluorite",
  "pyrite",
  "hematite",
  "magnetite",
  "galena",
  "azurite",
  "chrysocolla",
  "gold nugget",
  "silver ore",
  "copper ore",
  "iron ore",
  "coal",
  "amber",
  "jet",
  "coral stone",
  "ivory",
  "bone",
  "shell",
  "mother of pearl",
  "abalone shell",
  "geode",
  "crystal cluster",
  "stalactite",
  "stalagmite",
  "cave formation",
  "hot spring",
  "geyser",
  "mud pot",
  "fumarole",
  "volcanic vent",
  "lava flow",
  "lava tube",
  "volcanic crater",
  "caldera",
  "cinder cone",
  "shield volcano",
  "stratovolcano",
  "volcanic ash",
  "pumice",
  "obsidian glass",
  "basalt columns",
  "granite cliff",
  "sandstone arch",
  "limestone cave",
  "marble quarry",
  "slate roof",
  "shale layers",
  "conglomerate rock",
  "breccia",
  "schist",
  "gneiss",
  "quartzite",
  "soapstone",
  "serpentine",
  "travertine",
  "tufa tower",
  "petrified forest",
  "fossil bed",
  "dinosaur bones",
  "mammoth skeleton",
  "trilobite fossil",
  "ammonite fossil",
  "fern fossil",
  "fish fossil",
  "insect in amber",
  "footprint fossil",
  "coprolite",
  "stromatolite",
  "crinoid",
  "brachiopod",
  "gastropod fossil",
  "sea lily",
  "shark tooth",
  "whale bone",
  "woolly rhino",
  "saber tooth",
  "giant sloth",
  "terror bird",
  "pterosaur",
  "plesiosaur",
  "mosasaur",
  "ichthyosaur",
  "tyrannosaurus",
  "velociraptor",
  "triceratops",
  "stegosaurus",
  "brachiosaurus",
  "ankylosaurus",
  "parasaurolophus",
  "spinosaurus",
  "allosaurus",
  "diplodocus",
  "apatosaurus",
  "archaeopteryx",
  "dodo",
  "passenger pigeon",
  "great auk",
  "tasmanian tiger",
  "quagga",
  "irish elk",
  "moa",
  "elephant bird",
  "cave bear",
  "dire wolf",
  "mastodon",
  "glyptodon",
  "megatherium",
  "titanoboa",
  "megalodon",
  "dunkleosteus",
  "anomalocaris",
  "hallucigenia",
  "opabinia",
  "pikaia",
  "tiktaalik",
  "dimetrodon",
  "gorgonopsid",
  "cynognathus",
  "lystrosaurus",
  "eryops",
  "diplocaulus",
  "tully monster",
  "sea scorpion",
  "giant dragonfly",
  "giant millipede",
  "ancient fern",
  "seed fern",
  "cycad",
  "ginkgo",
  "horsetail",
  "club moss",
  "liverwort",
  "moss",
  "lichen",
  "algae",
  "kelp forest",
  "seagrass",
  "mangrove",
  "cypress swamp",
  "redwood grove",
  "sequoia",
  "bristlecone pine",
  "baobab",
  "banyan",
  "fig tree",
  "oak tree",
  "maple tree",
  "birch tree",
  "willow tree",
  "cherry tree",
  "apple tree",
  "orange tree",
  "lemon tree",
  "olive tree",
  "palm tree",
  "coconut palm",
  "date palm",
  "joshua tree",
  "saguaro cactus",
  "barrel cactus",
  "prickly pear",
  "agave",
  "aloe vera",
  "yucca",
  "dragon tree",
  "bottle tree",
  "kapok tree",
  "ceiba",
  "mahogany",
  "teak",
  "ebony",
  "rosewood",
  "sandalwood",
  "cedar",
  "cypress",
  "juniper",
  "spruce",
  "fir tree",
  "pine tree",
  "hemlock",
  "yew tree",
  "larch",
  "monkey puzzle",
  "araucaria",
  "kauri",
  "podocarp",
  "tree fern",
  "staghorn fern",
  "birds nest fern",
  "maidenhair fern",
  "bracken",
  "cinnamon fern",
  "royal fern",
  "ostrich fern",
  "boston fern",
  "asparagus fern",
  "foxtail fern",
  "rabbit foot fern",
  "brake fern",
  "holly fern",
  "leather fern",
  "resurrection fern",
  "water fern",
  "floating fern",
  "mosquito fern",
  "water lettuce",
  "duckweed",
  "water hyacinth",
  "water lily",
  "lotus",
  "sacred lotus",
  "victoria lily",
  "amazon lily",
  "calla lily",
  "peace lily",
  "spider lily",
  "rain lily",
  "fire lily",
  "tiger lily",
  "easter lily",
  "stargazer lily",
  "asiatic lily",
  "oriental lily",
  "trumpet lily",
  "martagon lily",
  "turks cap lily",
  "canada lily",
  "madonna lily",
  "regal lily",
  "golden lily",
];
