export const randomPrompts = [
  "old barn weathered wood",
  "cobblestone street pattern",
  "wrought iron gate detail",
  "tree roots twisted",
  "lichen on stone",
  "cracked mud patterns",
  "frost crystalline",
  "water droplet reflection",
  "spiderweb with dew",
  "feather fine detail",
  "eye close up",
  "lips parted",
  "hands touching",
  "feet in sand",
  "fingers interlaced",
  "scar tissue",
  "wrinkles and age",
  "hair texture",
  "skin pores macro",
  "eye lashes",
  "butterfly wing pattern",
  "snake skin texture",
  "turtle shell geometric",
  "fish scales shimmering",
  "bird feathers ruffled",
  "peacock eye spot",
  "moth wing patterns",
  "bee on honeycomb",
  "ant trail",
  "spider silk geometric",
  "dragonfly wing veins",
  "cicada shell hollow",
  "tree bark rough",
  "tree rings concentric",
  "pine cone spiral",
  "fern frond unfurling",
  "mushroom gill pattern",
  "moss soft growth",
  "fungus bracket",
  "lichen colorful",
  "dandelion seed dispersal",
  "plant thorns sharp",
  "cactus spines",
  "thistle prickly",
  "rose thorn",
  "blackberry bramble",
  "lotus seed pod",
  "poppy seed pod",
  "corn silk strand",
  "wheat grain close",
  "grass blade edge",
  "flower stamen",
  "petal veins",
  "leaf vein network",
  "branch bare winter",
  "gnarled tree trunk",
  "fallen log rotting",
  "stump rings",
  "roots surface",
  "vine climbing",
  "rope fiber",
  "twine twisted",
  "wire coil",
  "chain link",
  "net mesh",
  "lattice pattern",
  "fence posts shadow",
  "staircase spiral",
  "staircase shadow",
  "architectural arch",
  "colonnade receding",
  "doorway tunnel",
  "window panes grid",
  "shutter slats",
  "blind stripes",
  "radiator grille",
  "brick wall pattern",
  "stone wall texture",
  "concrete seams",
  "asphalt cracks",
  "railroad tracks perspective",
  "train tracks converge",
  "utility lines crossing",
  "power lines shadow",
  "telephone poles",
  "roof tile overlap",
  "shingle pattern",
  "gutter rust",
  "drain pipe curve",
  "antenna silhouette",
  "clock face",
  "gear teeth",
  "watch mechanism",
  "watch spring",
  "compass rose",
  "sundial shadow",
  "thermometer mercury",
  "barometer pressure",
  "ruler measurement",
  "gauge needle",
  "speedometer dial",
  "scale weight",
  "mirror reflection distorted",
  "prism light refracted",
  "lens bubble",
  "glass smooth",
  "glass shattered",
  "ice crystal formation",
  "frost window pattern",
  "water ripple concentric",
  "puddle reflection",
  "rain streaks",
  "snow drift edge",
  "sand ripple",
  "sand dune shadow",
  "mud crack",
  "clay texture",
  "ceramic glaze",
  "pottery thrown",
  "marble veins",
  "granite speckled",
  "slate layered",
  "limestone porous",
  "basalt dark",
  "coal chunk",
  "coal dust",
  "charcoal fragment",
  "ash residue",
  "rust oxide",
  "patina aged",
  "tarnish dark",
  "verdigris green",
  "silver mirror",
  "gold leaf",
  "copper shine",
  "bronze sculptural",
  "aluminum anodized",
  "titanium brushed",
  "steel grain",
  "iron wrought",
  "nickel plated",
  "chrome reflective",
  "brass ornamental",
  "pewter dull",
  "lead dense",
  "zinc coating",
  "tin can",
  "copper wire",
  "aluminum foil crumpled",
  "steel wool texture",
  "chain mail interlocking",
  "fishing net",
  "barbed wire",
  "razor wire",
  "gate lock",
  "padlock weathered",
  "key ornate",
  "nail rusty",
  "screw thread",
  "bolt hexagonal",
  "rivet pop",
  "weld seam",
  "hinge creak",
  "doorknob brass",
  "door latch",
  "deadbolt mechanism",
  "lock mechanism",
  "safe steel",
  "treasure chest",
  "jewelry box",
  "music box",
  "clock mechanism",
  "music box spring",
  "camera shutter",
  "lens aperture",
  "film strip",
  "photographic plate",
  "darkroom enlarger",
  "tripod legs",
  "light stand",
  "umbrella reflector",
  "softbox diffuser",
  "flags shade",
  "bounce card",
  "backdrop stand",
  "seismic wave",
  "sound wave",
  "light wave",
  "ripple concentric",
  "wave interference",
  "static pattern",
  "noise grain",
  "pixelated image",
  "halftone dot",
  "moiré pattern",
  "tessellation geometric",
  "tessellation islamic",
  "mandala intricate",
  "fractal recursive",
  "fractal zoom",
  "spiral golden ratio",
  "fibonacci spiral",
  "hexagon honeycomb",
  "pentagon symmetry",
  "octagon shape",
  "kaleidoscope pattern",
  "symmetry bilateral",
  "symmetry radial",
  "asymmetry balance",
  "composition rule thirds",
  "diagonal leading line",
  "vanishing point",
  "depth perspective",
  "shallow depth field",
  "bokeh blur",
  "motion blur speed",
  "focus soft",
  "focus sharp",
  "silhouette backlit",
  "rim light glow",
  "three point lighting",
  "studio lighting setup",
  "natural window light",
  "golden hour glow",
  "blue hour dusk",
  "harsh midday sun",
  "soft overcast",
  "shadow deep",
  "shadow cast",
  "shadow play",
  "light leak",
  "lens flare",
  "god rays crepuscular",
  "dust particles light",
  "cigarette smoke",
  "steam rising",
  "fog mist",
  "clouds dramatic",
  "storm approaching",
  "lightning strike",
  "rainbow after rain",
  "halo moon",
  "halo sun",
  "aurora borealis",
  "meteor shower",
  "comet tail",
  "milky way stars",
  "star trails",
  "eclipse shadow",
  "solar corona",
  "moon craters",
  "moon phases",
  "lunar eclipse",
  "sunrise gradient",
  "sunset gradient",
  "twilight purple",
  "night sky dark",
  "full moon bright",
  "new moon dark",
  "crescent moon thin",
  "moon rising",
  "moon setting",
  "sun flare",
  "sun disk",
  "sun spot",
  "sun ray",
  "sunburst starburst",
  "light painting",
  "light trail",
  "fire trail",
  "sparkler trace",
  "glow neon",
  "glow bioluminescent",
  "glow infrared",
  "thermal image",
  "x-ray image",
  "microscope slide",
  "dna helix",
  "cell division",
  "bacteria colonies",
  "coral polyp",
  "blood cells",
  "nerve fiber",
  "muscle fiber",
  "skin layer cross section",
  "tooth cross section",
  "bone marrow",
  "hair follicle",
  "sweat gland",
  "nerve ending",
  "synapse connection",
  "neuron dendrite",
  "eye retina",
  "ear canal",
  "nose septum",
  "lung bronchi",
  "heart chambers",
  "blood vessel",
  "artery pulse",
  "vein tributary",
  "lymph node",
  "gland tissue",
  "organ tissue",
  "tissue sample",
  "surgical instruments",
  "stethoscope coil",
  "syringe needle",
  "thermometer mercury",
  "blood pressure cuff",
  "pulse oximeter",
  "ecg electrode",
  "ultrasound probe",
  "endoscope tube",
  "microscope lens",
  "telescope view",
  "periscope mirror",
  "kaleidoscope view",
  "magnifying glass",
  "prism rainbow",
  "crystal geometric",
  "diamond facet",
  "gemstone brilliant",
  "pearl lustrous",
  "opal iridescent",
  "tourmaline striped",
  "quartz raw",
  "amethyst geode",
  "agate band",
  "fossil impression",
  "amber inclusion",
  "shell spiral",
  "nautilus chamber",
  "conch opening",
  "clam shell",
  "scallop shell",
  "mussel shell",
  "oyster shell",
  "coral skeleton",
  "sea urchin shell",
  "starfish arm",
  "sand dollar pattern",
  "sea biscuit",
  "bone fossil",
  "mammoth tusk",
  "dinosaur egg",
  "trilobite",
  "ammonite spiral",
  "belemnite stone",
  "petrified wood",
  "dinosaur track",
  "footprint sand",
  "handprint clay",
  "fingerprint ridge",
  "palm print",
  "lip print",
  "tooth mark",
  "claw mark",
  "hoof print",
  "paw print",
  "wing print dust",
  "tire track",
  "boot print",
  "shoe print",
  "skateboard mark",
  "bicycle tire",
  "motorcycle tire",
  "car tire tread",
  "truck tire",
  "train track gauge",
  "railroad tie",
  "railroad spike",
  "rail joint",
  "bumper coupler",
  "coupling chain",
  "brake wheel",
  "wheel spoke",
  "wheel rim",
  "tire valve",
  "wheel balance weight",
  "lug nut",
  "axle bearing",
  "suspension spring",
  "shock absorber",
  "brake rotor",
  "brake caliper",
  "brake pad",
  "brake hose",
  "throttle cable",
  "accelerator pedal",
  "brake pedal",
  "clutch pedal",
  "parking brake lever",
  "gear shift",
  "steering wheel",
  "steering column",
  "tie rod",
  "ball joint",
  "control arm",
  "stabilizer bar",
  "engine block",
  "cylinder head",
  "valve cover",
  "oil pan",
  "drain plug",
  "engine filter",
  "oil filter can",
  "fuel injector",
  "spark plug",
  "ignition coil",
  "alternator pulley",
  "serpentine belt",
  "timing chain",
  "timing gear",
  "camshaft lobe",
  "crankshaft",
  "piston rod",
  "connecting rod",
  "piston crown",
  "cylinder wall",
  "combustion chamber",
  "exhaust manifold",
  "muffler can",
  "tailpipe end",
  "catalytic converter",
  "transmission pan",
  "transmission filter",
  "torque converter",
  "gear tooth",
  "clutch disc",
  "flywheel",
  "driveshaft",
  "u-joint",
  "universal joint",
  "differential",
  "ring gear",
  "pinion gear",
  "cv joint",
  "cv axle",
  "motor mount",
  "transmission mount",
  "floor rust hole",
  "body panel dent",
  "windshield crack",
  "window tint",
  "door panel gap",
  "trim clip",
  "weather stripping",
  "door seal",
  "trunk seal",
  "hood hinge",
  "trunk hinge",
  "door hinge",
  "tailgate hinge",
  "latch mechanism",
  "handle lever",
  "pull handle",
  "door pocket",
  "cup holder",
  "armrest button",
  "seat spring",
  "seat frame",
  "seat belt webbing",
  "seat belt mechanism",
  "headrest",
  "backrest angle",
  "lumbar support",
  "side bolster",
  "seat cushion",
  "steering wheel grip",
  "steering wheel spoke",
  "horn ring",
  "turn signal stalk",
  "wiper stalk",
  "light switch",
  "window button",
  "lock button",
  "mirror switch",
  "seat control",
  "temperature dial",
  "fan speed knob",
  "radio dial",
  "volume knob",
  "tuning knob",
  "visor clip",
  "sun visor",
  "mirror visor",
  "headlamp switch",
  "fog lamp switch",
  "door lock mechanism",
  "electric window motor",
  "power window switch",
  "mirror motor",
  "window regulator",
  "roller track",
  "guide rail",
  "cable pulley",
  "motor coupling",
  "transmission torque",
  "engine vacuum",
  "fuel line connector",
  "coolant hose clamp",
  "hose barb",
  "fitting adapter",
  "quick connect coupler",
  "hydraulic fitting",
  "brake line fitting",
  "brake bleeder valve",
  "caliper bracket",
  "brake pad shim",
  "rotor vane",
  "rotor hat",
  "caliper piston",
  "wheel cylinder",
  "wheel bearing",
  "bearing race",
  "bearing roller",
  "bearing shield",
  "axle nut",
  "wheel stud",
  "lug nut pattern",
  "center cap",
  "wheel weight",
  "tire bead",
  "tire sidewall",
  "tire groove",
  "tire sipe",
  "tire compound",
  "tire repair patch",
  "inner tube valve",
  "tire plug",
  "tire puncture",
  "tire bubble",
  "tire wear indicator",
  "tread depth gauge",
  "tire rotation mark",
  "tire date code",
  "tire load index",
  "tire speed rating",
  "tire pressure monitor",
  "tire sensor",
  "tire balance weight",
  "tire valve cap",
  "suspension geometry",
  "wheel camber",
  "wheel toe",
  "caster angle",
  "ride height",
  "suspension travel",
  "spring compression",
  "spring rate",
  "damper resistance",
  "sway bar link",
  "bushings rubber",
  "strut mount bearing",
  "strut tower brace",
  "strut brace",
  "cross member",
  "subframe attachment",
  "engine cradle",
  "frame rail",
  "frame crossmember",
  "frame weld",
  "body seam",
  "body filler",
  "bondo repair",
  "primer coat",
  "paint layer",
  "clear coat",
  "accent stripe",
  "racing stripe",
  "door stripe",
  "hood stripe",
  "side stripe",
  "roof stripe",
  "two-tone paint",
  "gradient fade",
  "pearl effect",
  "metallic finish",
  "matte finish",
  "satin finish",
  "gloss finish",
  "custom paint",
  "vinyl wrap",
  "decal sticker",
  "window decal",
  "bumper sticker",
  "license plate holder",
  "license plate frame",
  "bumper guard",
  "bumper lip",
  "bumper splitter",
  "front spoiler",
  "side skirt",
  "rear diffuser",
  "roof spoiler",
  "trunk spoiler",
  "wing endplate",
  "aerodynamic element",
  "vortex generator",
  "roof rack",
  "roof basket",
  "cargo box",
  "bike rack mount",
  "tow hitch",
  "hitch receiver",
  "hitch ball",
  "trailer connector",
  "trailer light",
  "trailer brake",
  "trailer suspension",
  "cargo tie down",
  "cargo net",
  "bungee cord",
  "ratchet strap",
  "cargo liner",
  "floor mat rubber",
  "trunk mat",
  "cargo organizer",
  "tool box",
  "emergency kit",
  "first aid kit",
  "jack stand",
  "tire repair kit",
  "jumper cable",
  "battery terminal",
  "battery clamp",
  "battery tie down",
  "battery acid",
  "battery case",
  "battery cell",
  "cell separator",
  "cell terminal",
  "alternator terminal",
  "starter motor",
  "starter solenoid",
  "starter pinion",
  "flywheel ring gear",
  "ignition switch",
  "key blank",
  "key groove",
  "lock cylinder",
  "lock plug",
  "lock spring",
  "lock pin",
  "key housing",
  "remote fob",
  "fob button",
  "transmitter circuit",
  "receiver antenna",
  "alarm system",
  "alarm siren",
  "horn speaker",
  "audio speaker",
  "speaker magnet",
  "speaker coil",
  "speaker cone",
  "amplifier circuit",
  "amplifier heatsink",
  "capacitor can",
  "resistor color",
  "diode stripe",
  "transistor pin",
  "integrated circuit",
  "chip capacitor",
  "surface mount",
  "solder joint",
  "solder bridge",
  "pcb trace",
  "circuit board",
  "ground plane",
  "via hole",
  "component pad",
  "connector pin",
  "connector socket",
  "ribbon cable",
  "flat cable",
  "twisted pair",
  "shielded cable",
  "coaxial cable",
  "rj45 connector",
  "usb connector",
  "power connector",
  "fuse holder",
  "fuse wire",
  "relay coil",
  "relay contact",
  "relay spring",
  "relay armature",
  "contactor",
  "transformer coil",
  "transformer core",
  "inductor coil",
  "choke coil",
  "variable resistor",
  "potentiometer dial",
  "rheostat element",
  "trimmer potentiometer",
  "photoresistor cell",
  "thermistor bead",
  "pressure sensor",
  "temperature sensor",
  "oxygen sensor",
  "lambda probe",
  "mass air flow",
  "throttle position",
  "manifold absolute pressure",
  "knock sensor",
  "detonation sensor",
  "cam position sensor",
  "crank position sensor",
  "wheel speed sensor",
  "vehicle speed sensor",
  "yaw rate sensor",
  "accelerometer axis",
  "gyroscope sensor",
  "compass magnetometer",
  "infrared sensor",
  "proximity sensor",
  "motion detector",
  "touch sensor",
  "pressure switch",
  "float switch",
  "temperature switch",
  "micro switch",
  "limit switch",
  "emergency button",
  "pushbutton switch",
  "toggle switch",
  "rocker switch",
  "slide switch",
  "dimmer switch",
  "touch switch",
  "capacitive touch",
  "moisture sensor",
  "humidity sensor",
  "carbon monoxide",
  "natural gas detector",
  "smoke detector",
  "flame detector",
  "camera sensor",
  "image sensor",
  "focal plane",
  "color filter array",
  "pixel well",
  "pixel transistor",
  "analog to digital",
  "digital to analog",
  "clock generator",
  "power supply regulator",
  "voltage reference",
  "ground connection",
  "power distribution",
  "current limiting",
  "thermal shutdown",
  "watchdog timer",
  "interrupt priority",
  "memory address",
  "data bus",
  "control bus",
  "address bus",
  "register stack",
  "cache hierarchy",
  "memory cell",
  "flip flop gate",
  "logic gate",
  "transistor base",
  "transistor collector",
  "transistor emitter",
  "drain source gate",
  "mosfet channel",
  "source follower",
  "cascode configuration",
  "differential pair",
  "current mirror",
  "voltage reference",
  "output impedance",
  "input impedance",
  "bandwidth limiting",
  "frequency response",
  "phase shift",
  "gain margin",
  "stability criterion",
  "noise figure",
  "signal to noise ratio",
  "distortion harmonic",
  "intermodulation",
  "spurious emission",
  "adjacent channel",
  "out of band",
  "blocking dynamic range",
  "compression point",
  "1db compression",
  "ip3 intercept",
  "noise floor",
  "sensitivity receiver",
  "selectivity filter",
  "image rejection",
  "local oscillator",
  "mixer nonlinearity",
  "heterodyne conversion",
  "intermediate frequency",
  "crystal oscillator",
  "phase locked loop",
  "frequency divider",
  "frequency synthesizer",
  "modulation scheme",
  "demodulation circuit",
  "baseband filter",
  "nyquist rate",
  "sampling theorem",
  "quantization error",
  "dither noise",
  "sigma delta",
  "oversampling",
  "decimation filter",
  "interpolation",
  "rate conversion",
  "polyphase filter",
  "windowing function",
  "fft algorithm",
  "dft computation",
  "convolution",
  "correlation",
  "autocorrelation",
  "cross correlation",
  "power spectral density",
  "white noise",
  "pink noise",
  "brown noise",
  "colored noise",
  "noise shaping",
  "signal conditioning",
  "impedance matching",
  "transformer coupling",
  "ac coupling",
  "dc blocking",
  "high pass filter",
  "low pass filter",
  "band pass filter",
  "notch filter",
  "butterworth response",
  "chebyshev response",
  "bessel response",
  "elliptic response",
  "filter order",
  "cutoff frequency",
  "filter Q",
  "resonance peak",
  "damping ratio",
  "natural frequency",
  "transient response",
  "steady state",
  "impulse response",
  "step response",
  "ringing overshoot",
  "settling time",
  "rise time",
  "fall time",
  "propagation delay",
  "setup time",
  "hold time",
  "metastability",
  "race condition",
  "glitch logic",
  "hazard logic",
  "redundant path",
  "feedback path",
  "loop gain",
  "loop filter",
  "loop delay",
  "oscillation frequency",
  "damping oscillation",
  "control loop",
  "feedback amplifier",
  "closed loop gain",
  "open loop gain",
  "loop stability",
  "bode plot",
  "nyquist plot",
  "nichols plot",
  "root locus",
  "pole location",
  "zero location",
  "transfer function",
  "system response",
  "step input",
  "impulse input",
  "sinusoidal input",
  "chirp input",
  "noise input",
  "maximum likelihood",
  "least squares",
  "optimization algorithm",
  "gradient descent",
  "newton method",
  "levenberg marquardt",
  "genetic algorithm",
  "simulated annealing",
  "particle swarm",
  "ant colony",
  "artificial neural network",
  "deep learning",
  "convolutional network",
  "recurrent network",
  "long short term memory",
  "gated recurrent",
  "attention mechanism",
  "transformer network",
  "self attention",
  "multi head attention",
  "positional encoding",
  "embedding layer",
  "softmax output",
  "cross entropy loss",
  "backpropagation",
  "gradient computation",
  "weight update",
  "learning rate",
  "momentum optimizer",
  "adam optimizer",
  "batch normalization",
  "layer normalization",
  "dropout regularization",
  "weight decay",
  "early stopping",
  "cross validation",
  "training curve",
  "validation curve",
  "test accuracy",
  "confusion matrix",
  "precision recall",
  "f1 score",
  "roc curve",
  "auc metric",
  "class imbalance",
  "data augmentation",
  "transfer learning",
  "fine tuning",
  "feature extraction",
  "dimensionality reduction",
  "principal component analysis",
  "independent component",
  "clustering algorithm",
  "kmeans clustering",
  "hierarchical clustering",
  "dbscan clustering",
  "gaussian mixture",
  "expectation maximization",
  "markov chain",
  "hidden markov model",
  "viterbi algorithm",
  "baum welch",
  "forward backward",
  "conditional random field",
  "structured prediction",
  "sequence labeling",
  "part of speech",
  "named entity",
  "semantic role",
  "dependency parsing",
  "constituency parsing",
  "abstract syntax tree",
  "parse tree",
  "derivation tree",
  "grammar rule",
  "production rule",
  "lexicon entry",
  "word sense",
  "semantic representation",
  "knowledge graph",
  "entity relation",
  "ontology class",
  "inference rule",
  "resolution proof",
  "unification algorithm",
  "logic programming",
  "prolog clause",
  "backtracking search",
  "cut operator",
  "negation failure",
  "assert retract",
  "dynamic predicate",
  "static predicate",
  "built in predicate",
  "findall bagof",
  "setof aggregate",
  "sort operation",
  "keysort operation",
  "msort operation",
  "list operation",
  "append operation",
  "reverse operation",
  "member operation",
  "length operation",
  "nth operation",
  "last operation",
  "select operation",
  "permutation operation",
  "subset operation",
  "intersection operation",
  "union operation",
  "difference operation",
  "symmetric difference",
  "cartesian product",
  "power set",
  "combinatorial number",
  "binomial coefficient",
  "factorial operation",
  "gcd algorithm",
  "lcm algorithm",
  "prime factorization",
  "modular arithmetic",
  "greatest common divisor",
  "extended euclidean",
  "fermat little theorem",
  "euler totient",
  "chinese remainder",
  "quadratic residue",
  "legendre symbol",
  "jacobi symbol",
  "gaussian integer",
  "eisenstein integer",
  "algebraic number",
  "transcendental number",
  "irrational number",
  "rational approximation",
  "continued fraction",
  "convergent fraction",
  "farey sequence",
  "stern brocot tree",
  "calkin wilf tree",
  "minkowski question mark",
  "cantor set",
  "sierpinski triangle",
  "menger sponge",
  "julia set",
  "mandelbrot set",
  "lorenz attractor",
  "strange attractor",
  "butterfly effect",
  "chaotic dynamics",
  "periodic orbit",
  "lyapunov exponent",
  "bifurcation diagram",
  "phase portrait",
  "phase space",
  "state space",
  "configuration space",
  "parameter space",
  "solution curve",
  "integral curve",
  "vector field",
  "flow line",
  "stream line",
  "streamline pattern",
  "vortex core",
  "stagnation point",
  "separation point",
  "reattachment point",
  "shock wave",
  "expansion fan",
  "mach cone",
  "sound barrier",
  "supersonic flow",
  "transonic flow",
  "subsonic flow",
  "hypersonic flow",
  "rarefied gas",
  "continuum flow",
  "turbulent flow",
  "laminar flow",
  "transitional flow",
  "boundary layer",
  "shear layer",
  "vortex sheet",
  "vortex pair",
  "vortex ring",
  "vortex tube",
  "vortex street",
  "karman vortex",
  "standing wave",
  "traveling wave",
  "shock boundary",
  "rarefaction wave",
  "gravity wave",
  "capillary wave",
  "surface wave",
  "internal wave",
  "shallow water wave",
  "deep water wave",
  "seismic wave",
  "love wave",
  "rayleigh wave",
  "p wave",
  "s wave",
  "electromagnetic wave",
  "radio wave",
  "microwave frequency",
  "terahertz wave",
  "infrared wave",
  "ultraviolet wave",
  "x ray wave",
  "gamma ray wave",
  "particle accelerator",
  "electron beam",
  "ion beam",
  "plasma state",
  "bose einstein condensate",
  "quantum tunneling",
  "quantum entanglement",
  "quantum superposition",
  "wave particle duality",
  "uncertainty principle",
  "planck constant",
  "fine structure",
  "atomic shell",
  "electron orbital",
  "orbital shape",
  "probability density",
  "spin magnetic moment",
  "orbital angular momentum",
  "total angular momentum",
  "quantum number",
  "pauli exclusion",
  "aufbau principle",
  "hund rule",
  "orbital hybridization",
  "bonding orbital",
  "antibonding orbital",
  "molecular orbital",
  "pi bond",
  "sigma bond",
  "coordinate covalent",
  "ionic bond",
  "hydrogen bond",
  "van der waals force",
  "london dispersion",
  "dipole moment",
  "electronegativity difference",
  "chemical potential",
  "redox potential",
  "oxidation state",
  "reduction oxidation",
  "electron transfer",
  "proton transfer",
  "acid base reaction",
  "buffer solution",
  "titration curve",
  "equivalence point",
  "ph indicator",
  "buffer capacity",
  "polyprotic acid",
  "salt hydrolysis",
  "amphoteric substance",
  "zuwitterion form",
  "isoelectric point",
  "enzyme kinetics",
  "enzyme substrate",
  "enzyme active site",
  "enzyme inhibition",
  "competitive inhibitor",
  "noncompetitive inhibitor",
  "enzyme cofactor",
  "enzyme coenzyme",
  "enzyme prosthetic group",
  "apoenzyme form",
  "holoenzyme form",
  "enzyme turnover",
  "enzyme efficiency",
  "catalyst mechanism",
  "transition state",
  "activation energy",
  "reaction coordinate",
  "reaction intermediate",
  "reaction rate",
  "reaction order",
  "half life decay",
  "first order kinetics",
  "second order kinetics",
  "zero order kinetics",
  "pseudo first order",
  "steady state approximation",
  "pre equilibrium approximation",
  "lindemann mechanism",
  "chain reaction mechanism",
  "branching chain",
  "termination step",
  "initiation step",
  "propagation step",
  "elementary reaction",
  "rate determining step",
  "collision theory",
  "steric factor",
  "orientation factor",
  "activation frequency",
  "hard sphere model",
  "reaction cross section",
  "mean free path",
  "collision frequency",
  "average molecular speed",
  "maxwell boltzmann distribution",
  "boltzmann constant",
  "absolute temperature",
  "thermal energy",
  "kinetic energy",
  "potential energy",
  "total energy",
  "energy conservation",
  "energy dissipation",
  "entropy increase",
  "entropy decrease",
  "gibbs free energy",
  "enthalpy change",
  "entropy change",
  "spontaneity condition",
  "equilibrium constant",
  "reaction quotient",
  "le chatelier principle",
  "dynamic equilibrium",
  "static equilibrium",
  "chemical equilibrium",
  "solubility equilibrium",
  "solubility product",
  "common ion effect",
  "ion product water",
  "autoionization water",
  "water dissociation",
  "hydronium ion",
  "hydroxide ion",
  "water as solvent",
  "aqueous solution",
  "colloidal solution",
  "suspension mixture",
  "emulsion mixture",
  "colloid particle",
  "colloidal dispersion",
  "tyndall effect",
  "brownian motion",
  "osmotic pressure",
  "vapor pressure",
  "boiling point elevation",
  "freezing point depression",
  "activity coefficient",
  "ionic strength",
  "debye huckel theory",
  "ion pair formation",
  "complex ion",
  "coordination chemistry",
  "ligand field theory",
  "crystal field theory",
  "crystal field splitting",
  "d orbital splitting",
  "octahedral complex",
  "tetrahedral complex",
  "square planar complex",
  "linear complex",
  "ligand type",
  "strong field ligand",
  "weak field ligand",
  "spectrochemical series",
  "electron configuration",
  "ground state",
  "excited state",
  "term symbol",
  "multiplicity spin",
  "spin allowed transition",
  "spin forbidden transition",
  "selection rule",
  "transition forbidden",
  "allowed transition",
  "absorption spectrum",
  "emission spectrum",
  "fluorescence emission",
  "phosphorescence emission",
  "radiative decay",
  "non radiative decay",
  "internal conversion",
  "auger electron",
  "bremsstrahlung radiation",
  "cherenkov radiation",
  "synchrotron radiation",
  "cyclotron radiation",
  "magnetron tube",
  "klystron tube",
  "traveling wave tube",
  "crossed field interaction",
  "electron bunching",
  "velocity focusing",
  "magnetic focusing",
  "electrostatic focusing",
  "acceleration voltage",
  "deflection voltage",
  "beam current",
  "brightness temperature",
  "antenna radiation pattern",
  "main lobe gain",
  "side lobe level",
  "antenna beamwidth",
  "half power beamwidth",
  "directivity antenna",
  "gain antenna",
  "radiation efficiency",
  "impedance matching",
  "return loss",
  "standing wave ratio",
  "reflection coefficient",
  "transmission coefficient",
  "smith chart",
  "impedance transformation",
  "matching network",
  "lumped element circuit",
  "distributed circuit",
  "transmission line",
  "coaxial cable",
  "waveguide",
  "resonant cavity",
  "quality factor q",
  "bandwidth resonant",
  "parallel resonance",
  "series resonance",
  "resonant frequency",
  "resonant impedance",
  "resonant admittance",
  "antiresonance frequency",
  "poles zeros",
  "bode magnitude",
  "bode phase",
  "gain magnitude db",
  "phase in degrees",
  "magnitude response",
  "phase response",
  "group delay",
  "phase delay",
  "nyquist sampling",
  "aliasing effect",
  "spectral leakage",
  "window function hamming",
  "window function hanning",
  "window function blackman",
  "window function kaiser",
  "spectral resolution",
  "frequency bin",
  "power spectrum",
  "welch method",
  "multitaper method",
  "periodogram estimate",
  "spectral estimation",
  "ar model",
  "ma model",
  "arma model",
  "autoregressive process",
  "moving average process",
  "yule walker equation",
  "levinson durbin algorithm",
  "lattice filter",
  "reflection coefficient",
  "partial correlation coefficient",
  "autocorrelation function",
  "cross correlation function",
  "wiener filter",
  "kalman filter",
  "particle filter",
  "hidden markov chain",
  "viterbi decoding",
  "forward algorithm",
  "backward algorithm",
  "baum welch algorithm",
  "expectation step",
  "maximization step",
  "likelihood function",
  "maximum likelihood estimate",
  "bayesian inference",
  "posterior distribution",
  "prior distribution",
  "likelihood ratio",
  "marginal likelihood",
  "evidence marginal",
  "bayes factor",
  "posterior odds",
  "credible interval",
  "highest density region",
  "variational inference",
  "mean field approximation",
  "gibbs sampling",
  "metropolis hastings",
  "hamiltonian monte carlo",
  "no u turn sampler",
  "slice sampling",
  "rejection sampling",
  "importance sampling",
  "sequential importance",
  "adaptive importance",
  "resampling step",
  "effective sample size",
  "sample weight",
  "numerical integration",
  "quadrature rule",
  "simpson rule",
  "trapezoidal rule",
  "gaussian quadrature",
  "monte carlo integration",
  "quasi monte carlo",
  "low discrepancy sequence",
  "sobol sequence",
  "halton sequence",
  "discrepancy measure",
  "stirling approximation",
  "laplace approximation",
  "saddle point approximation",
  "perturbation series",
  "asymptotic expansion",
  "singularity analysis",
  "branch cut",
  "branch point",
  "residue theorem",
  "contour integration",
  "laurent series",
  "power series expansion",
  "taylor series",
  "maclaurin series",
  "fourier series",
  "fourier coefficients",
  "fourier transform",
  "inverse fourier",
  "laplace transform",
  "inverse laplace",
  "z transform",
  "inverse z transform",
  "generating function",
  "characteristic function",
  "moment generating",
  "probability generating",
  "factorial moment",
  "central moment",
  "raw moment",
  "moment of inertia",
  "radius of gyration",
  "covariance matrix",
  "correlation matrix",
  "precision matrix",
  "partial correlation",
  "multiple correlation",
  "canonical correlation",
  "linear discriminant",
  "fisher discriminant",
  "mahalanobis distance",
  "euclidean distance",
  "manhattan distance",
  "chebyshev distance",
  "minkowski distance",
  "wasserstein distance",
  "earth mover distance",
  "kullback leibler divergence",
  "jensen shannon divergence",
  "hellinger distance",
  "bhattacharyya distance",
  "chi squared statistic",
  "kolmogorov smirnov test",
  "anderson darling test",
  "shapiro wilk test",
  "normality test",
  "homogeneity test",
  "goodness of fit",
  "contingency table",
  "chi square test",
  "fisher exact test",
  "mcnemar test",
  "cochran mantel haenszel",
  "log rank test",
  "wilcoxon signed rank",
  "mann whitney u test",
  "kruskal wallis test",
  "friedman test",
  "jonckheere trend test",
  "spearman correlation",
  "kendall tau correlation",
  "point biserial correlation",
  "polyserial correlation",
  "polychoric correlation",
  "tetrachoric correlation",
  "lambda statistic",
  "gamma statistic",
  "somers d",
  "somer asymmetric",
  "guttman coefficient",
  "cronbach alpha",
  "kuder richardson formula",
  "intraclass correlation",
  "agreement measure",
  "cohens kappa",
  "fleiss kappa",
  "krippendorff alpha",
  "reliability coefficient",
  "validity evidence",
  "construct validity",
  "content validity",
  "criterion validity",
  "convergent validity",
  "discriminant validity",
  "predictive validity",
  "concurrent validity",
  "sensitivity test",
  "specificity test",
  "positive predictive value",
  "negative predictive value",
  "receiver operating characteristic",
  "area under curve",
  "precision recall curve",
  "f measure",
  "balanced f measure",
  "matthews correlation",
  "youden index",
  "diagnostic odds ratio",
  "likelihood ratio positive",
  "likelihood ratio negative",
  "number needed treat",
  "number needed harm",
  "attributable risk",
  "relative risk",
  "odds ratio",
  "risk ratio",
  "hazard ratio",
  "incidence rate",
  "prevalence proportion",
  "cumulative incidence",
  "case fatality rate",
  "mortality rate",
  "morbidity rate",
  "attack rate",
  "secondary attack rate",
  "basic reproduction number",
  "effective reproduction number",
  "generation time",
  "serial interval",
  "latency period",
  "incubation period",
  "epidemic curve",
  "logistic growth",
  "exponential growth",
  "power law",
  "pareto distribution",
  "zipf distribution",
  "benford law",
  "zeta distribution",
  "poisson distribution",
  "binomial distribution",
  "multinomial distribution",
  "negative binomial",
  "hypergeometric distribution",
  "beta binomial",
  "dirichlet multinomial",
  "normal distribution",
  "lognormal distribution",
  "exponential distribution",
  "gamma distribution",
  "weibull distribution",
  "rayleigh distribution",
  "rice distribution",
  "nakagami distribution",
  "maxwell boltzmann distribution",
  "student t distribution",
  "snedecor f distribution",
  "chi squared distribution",
  "wishart distribution",
  "dirichlet distribution",
  "beta distribution",
  "uniform distribution",
  "triangular distribution",
  "trapezoidal distribution",
  "laplace distribution",
  "cauchy distribution",
  "logistic distribution",
  "gumbel distribution",
  "frechet distribution",
  "weibull shape",
  "gamma shape",
  "erlang distribution",
  "inverse gaussian",
  "wald distribution",
  "stable distribution",
  "levy distribution",
  "pareto type i",
  "pareto type ii",
  "generalized pareto",
  "burr distribution",
  "dagum distribution",
  "singh maddala distribution",
  "gb2 distribution",
  "johnson su transformation",
  "johnson sb transformation",
  "box cox transformation",
  "yeo johnson transformation",
  "quantile transformation",
  "probability integral",
  "inverse transform sampling",
  "acceptance rejection sampling",
  "adaptive rejection sampling",
  "alias method",
  "ziggurat algorithm",
  "ratio of uniforms",
  "source code generation",
  "executable program",
  "compiled binary",
  "interpreted script",
  "bytecode instruction",
  "assembly language",
  "machine code instruction",
  "cpu cycle time",
  "cpu clock speed",
  "instruction pipeline",
  "superscalar architecture",
  "branch prediction",
  "cache memory hierarchy",
  "cache line size",
  "cache associativity",
  "cache replacement policy",
  "tlb translation lookaside",
  "virtual address space",
  "physical memory address",
  "memory management unit",
  "page fault interrupt",
  "segmentation fault",
  "protection violation",
  "context switch overhead",
  "process scheduling",
  "thread scheduling",
  "preemptive scheduler",
  "non preemptive scheduler",
  "round robin scheduling",
  "priority queue scheduling",
  "multilevel feedback queue",
  "fair share scheduler",
  "load balancer",
  "work stealing algorithm",
  "task parallelism",
  "data parallelism",
  "pipeline parallelism",
  "gpu acceleration",
  "simd instruction",
  "thread divergence",
  "memory coalescing",
  "bank conflict",
  "warp execution",
  "occupancy utilization",
  "roofline model",
  "arithmetic intensity",
  "memory bandwidth",
  "compute bound",
  "memory bound",
  "latency hiding",
  "prefetching strategy",
  "speculative execution",
  "memory barrier",
  "cache coherency",
  "snooping protocol",
  "directory protocol",
  "consistency model",
  "sequential consistency",
  "causal consistency",
  "weak consistency",
  "release consistency",
  "acquire release semantic",
  "memory fence instruction",
  "atomic compare and swap",
  "lock free data structure",
  "wait free algorithm",
  "lock mechanism",
  "spin lock",
  "ticket lock",
  "monitor based synchronization",
  "condition variable",
  "semaphore counting",
  "barrier synchronization",
  "atomic variable",
  "volatile keyword",
  "thread local storage",
  "fiber lightweight",
  "coroutine continuation",
  "async await syntax",
  "promise future",
  "callback function",
  "event loop",
  "reactor pattern",
  "proactor pattern",
  "observer pattern",
  "state pattern",
  "strategy pattern",
  "template method pattern",
  "singleton pattern",
  "factory pattern",
  "builder pattern",
  "prototype pattern",
  "adapter pattern",
  "bridge pattern",
  "composite pattern",
  "decorator pattern",
  "facade pattern",
  "proxy pattern",
  "chain of responsibility",
  "command pattern",
  "interpreter pattern",
  "iterator pattern",
  "mediator pattern",
  "memento pattern",
  "visitor pattern",
  "mvc architecture",
  "mvp architecture",
  "mvvm architecture",
  "clean architecture",
  "hexagonal architecture",
  "event sourcing",
  "cqrs pattern",
  "saga pattern",
  "circuit breaker",
  "bulkhead pattern",
  "retry pattern",
  "timeout pattern",
  "cache aside pattern",
  "write through cache",
  "write behind cache",
  "load balancing",
  "round robin load",
  "least connection",
  "ip hash load",
  "resource pool",
  "connection pool",
  "thread pool executor",
  "future callback",
  "rxjava observable",
  "reactive stream",
  "backpressure handling",
  "buffering strategy",
  "windowing operation",
  "throttle debounce",
  "flatmap operator",
  "switchmap operator",
  "mergemap operator",
  "concatmap operator",
  "timeout error handling",
  "retry with backoff",
  "exponential backoff",
  "circuit breaker state",
  "graceful degradation",
  "fallback service",
  "bulkhead isolation",
  "blue green deployment",
  "canary deployment",
  "rolling deployment",
  "feature flag toggle",
  "ab testing framework",
  "analytics tracking",
  "performance monitoring",
  "distributed tracing",
  "logging aggregation",
  "metrics collection",
  "alerting rules",
  "incident response",
  "on call rotation",
  "postmortem analysis",
  "error budget",
  "slo definition",
  "sli measurement",
  "sla agreement",
  "uptime percentage",
  "availability metric",
  "reliability metric",
  "latency percentile",
  "throughput capacity",
  "scalability testing",
  "load testing",
  "stress testing",
  "spike testing",
  "endurance testing",
  "chaos engineering",
  "fault injection",
  "network partition",
  "latency injection",
  "packet loss simulation",
  "disk full scenario",
  "memory pressure",
  "cpu saturation",
  "context switch",
  "runqueue depth",
  "io wait time",
  "iowait percentage",
  "disk utilization",
  "disk throughput",
  "disk latency",
  "seek time",
  "rotational latency",
  "transfer time",
  "nvme protocol",
  "ssd controller",
  "flash memory cell",
  "wear leveling algorithm",
  "garbage collection ssd",
  "trim command",
  "overprovisioning ssd",
  "hdd platter",
  "read write head",
  "spindle motor",
  "actuator arm",
  "servo feedback",
  "track seeking",
  "head crash",
  "data recovery",
  "disk imaging",
  "forensic analysis",
  "file carving",
  "deleted file recovery",
  "data wiping",
  "secure erase",
  "dban sanitization",
  "cryptographic erase",
  "full disk encryption",
  "file level encryption",
  "database encryption",
  "column encryption",
  "transparent data encryption",
  "key management service",
  "hardware security module",
  "tpm module",
  "secure enclave",
  "trusted execution environment",
  "attestation proof",
  "remote attestation",
  "sealed storage",
  "key derivation function",
  "password hashing algorithm",
  "salt random",
  "pepper secret",
  "bcrypt algorithm",
  "scrypt algorithm",
  "argon2 algorithm",
  "pbkdf2 algorithm",
  "md5 hash legacy",
  "sha1 hash deprecated",
  "sha256 hash",
  "sha384 hash",
  "sha512 hash",
  "sha3 family",
  "blake2 hash",
  "blake3 hash",
  "murmur hash",
  "xxhash",
  "crc checksum",
  "adler checksum",
  "fletcher checksum",
  "hmac authentication",
  "digital signature",
  "rsa signature",
  "ecdsa signature",
  "dsa signature",
  "public key infrastructure",
  "certificate authority",
  "certificate chain",
  "certificate pinning",
  "certificate transparency",
  "x509 certificate",
  "certificate revocation",
  "ocsp stapling",
  "tls handshake",
  "ssl certificate",
  "cipher suite",
  "key exchange algorithm",
  "symmetric cipher",
  "aes encryption",
  "des encryption legacy",
  "3des triple",
  "rc4 cipher",
  "chacha20 cipher",
  "salsa20 cipher",
  "mode of operation",
  "ecb mode electronic",
  "cbc mode cipher",
  "ctr mode counter",
  "gcm mode galois",
  "ofb mode output",
  "cfb mode cipher",
  "padding oracle",
  "timing attack",
  "side channel attack",
  "power analysis",
  "electromagnetic analysis",
  "fault injection attack",
  "double encryption",
  "meet in the middle",
  "birthday paradox",
  "collision attack",
  "preimage attack",
  "rainbow table",
  "dictionary attack",
  "brute force attack",
  "password cracking",
  "password strength",
  "entropy bits",
  "password policy",
  "account lockout",
  "failed login attempt",
  "captcha challenge",
  "multi factor authentication",
  "one time password",
  "time based otp",
  "hmac based otp",
  "biometric authentication",
  "fingerprint scanner",
  "iris recognition",
  "facial recognition",
  "voice recognition",
  "gait recognition",
  "liveness detection",
  "spoofing attack",
  "replay attack",
  "man in the middle",
  "arp spoofing",
  "dns spoofing",
  "session hijacking",
  "cookie stealing",
  "token theft",
  "jwt token",
  "oauth authorization",
  "openid connect",
  "saml assertion",
  "kerberos protocol",
  "ldap directory",
  "active directory",
  "radius authentication",
  "tacacs authorization",
  "single sign on",
  "federated identity",
  "account provisioning",
  "access control list",
  "role based access",
  "attribute based access",
  "policy enforcement",
  "audit logging",
  "compliance reporting",
  "penetration testing",
  "vulnerability scanning",
  "security assessment",
  "threat modeling",
  "attack surface",
  "attack tree",
  "kill chain",
  "cyber kill chain",
  "mitre framework",
  "attack technique",
  "exploitation method",
  "privilege escalation",
  "lateral movement",
  "data exfiltration",
  "persistence backdoor",
  "command control",
  "obfuscation technique",
  "anti analysis",
  "packing executable",
  "code injection",
  "dll injection",
  "process hollowing",
  "hook function",
  "api hooking",
  "syscall hooking",
  "vmware escape",
  "hypervisor escape",
  "container escape",
  "kernel exploit",
  "kernel module",
  "rootkit behavior",
  "bookit firmware",
  "uefi firmware",
  "bios firmware",
  "secure boot",
  "measured boot",
  "trusted boot",
  "ota update",
  "rollback attack",
  "downgrade attack",
  "exploit kit",
  "zero day vulnerability",
  "worm propagation",
  "virus infection",
  "trojan horse",
  "ransomware encryption",
  "crypto locker",
  "wannacry attack",
  "petya attack",
  "mirai botnet",
  "dga domain generation",
  "c2 communication",
  "beaconing activity",
  "exfil channel",
  "dns tunneling",
  "http tunnel",
  "covert channel",
  "timing channel",
  "storage channel",
  "acoustic side channel",
  "heat map thermal",
  "smoke trail",
  "water flow",
  "wind pattern",
  "sand pattern",
  "dune formation",
  "erosion pattern",
  "sediment layer",
  "stratification geology",
  "fold structure",
  "fault line",
  "mineral vein",
  "crystal growth",
  "crystalline structure",
  "ice crystal formation",
  "snowflake geometry",
  "raindrop shape",
  "cloud formation",
  "cloud pattern",
  "contrail formation",
  "lenticular cloud",
  "mammatus cloud",
  "crepuscular ray",
  "shadow band",
  "light shaft",
  "god ray sun",
  "dust devil",
  "tornado funnel",
  "hurricane spiral",
  "weather front",
  "cold front",
  "warm front",
  "occluded front",
  "jet stream",
  "monsoon pattern",
  "trade wind",
  "sea breeze",
  "land breeze",
  "katabatic wind",
  "anabatic wind",
  "föhn wind",
  "chinook wind",
  "dust storm",
  "haboob wall",
  "derecho line",
  "microburst",
  "downburst",
  "gust front",
  "weather radar",
  "doppler shift",
  "storm tracking",
  "precipitation type",
  "rain rate",
  "hail size",
  "snow depth",
  "frost coverage",
  "rime formation",
  "glaze ice",
  "black ice",
  "sleet pellet",
  "freezing rain",
  "wet bulb temperature",
  "dew point",
  "relative humidity",
  "absolute humidity",
  "vapor pressure",
  "saturation deficit",
  "heat index",
  "wind chill",
  "apparent temperature",
  "thermal comfort",
  "microclimate variation",
  "urban heat island",
  "heat dome",
  "cold snap",
  "polar vortex",
  "el nino effect",
  "la nina effect",
  "climate oscillation",
  "north atlantic oscillation",
  "southern oscillation",
  "arctic oscillation",
  "madden julian",
  "monsoon index",
  "vegetation index",
  "ndvi normalized",
  "leaf area",
  "canopy density",
  "tree crown",
  "branch structure",
  "root system",
  "soil horizon",
  "soil texture",
  "soil structure",
  "soil compaction",
  "soil porosity",
  "water retention",
  "infiltration rate",
  "permeability soil",
  "hydraulic conductivity",
  "capillary rise",
  "water table",
  "groundwater flow",
  "aquifer storage",
  "artesian well",
  "spring emergence",
  "seep discharge",
  "wetland hydrology",
  "estuary mixing",
  "salt wedge intrusion",
  "tidal bore",
  "tidal current",
  "tidal flat",
  "salt marsh",
  "mangrove forest",
  "seagrass meadow",
  "kelp forest",
  "coral bleaching",
  "fish schooling",
  "migration route",
  "animal territory",
  "predator prey",
  "food web",
  "ecological succession",
  "pioneer species",
  "climax community",
  "biodiversity hotspot",
  "endemic species",
  "invasive species",
  "species extinction",
  "conservation status",
  "habitat fragmentation",
  "wildlife corridor",
  "protected area",
  "nature reserve",
  "ecosystem service",
  "carbon sequestration",
  "nutrient cycling",
  "pollination service",
  "seed dispersal",
  "decomposition process",
  "nitrogen cycle",
  "phosphorus cycle",
  "sulfur cycle",
  "carbon cycle",
  "biogeochemical cycling",
  "trophic level",
  "energy flow",
  "pyramid structure",
  "standing biomass",
  "productivity rate",
  "efficiency transfer",
  "ecological footprint",
  "carrying capacity",
  "population growth",
  "population decline",
  "population structure",
  "age pyramid",
  "sex ratio",
  "birth rate",
  "death rate",
  "immigration rate",
  "emigration rate",
  "natural increase",
  "total fertility",
  "life expectancy",
  "infant mortality",
  "disease prevalence",
  "endemic disease",
  "epidemic outbreak",
  "pandemic spread",
  "vector borne disease",
  "zoonotic disease",
  "antimicrobial resistance",
  "antibiotic resistance",
  "virulence factor",
  "pathogenicity determinant",
  "infection mechanism",
  "immune response",
  "adaptive immunity",
  "innate immunity",
  "antibody production",
  "t cell activation",
  "b cell differentiation",
  "memory cell",
  "plasma cell",
  "regulatory t cell",
  "cytokine signaling",
  "interferon response",
  "complement cascade",
  "phagocytosis process",
  "opsonization marking",
  "antigen presentation",
  "major histocompatibility",
  "t cell receptor",
  "b cell receptor",
  "clonal selection",
  "somatic hypermutation",
  "class switch recombination",
  "v d j recombination",
  "mutation mechanism",
  "dna repair pathway",
  "mismatch repair",
  "excision repair",
  "base excision",
  "nucleotide excision",
  "photoreactivation",
  "translesion synthesis",
  "apoptosis pathway",
  "necrosis cell death",
  "autophagy process",
  "senescence state",
  "telomere shortening",
  "oxidative stress",
  "reactive oxygen",
  "free radical",
  "antioxidant defense",
  "superoxide dismutase",
  "catalase enzyme",
  "glutathione peroxidase",
  "metallothionein protein",
  "heat shock protein",
  "chaperone function",
  "proteasome degradation",
  "ubiquitin tagging",
  "sumoylation modification",
  "phosphorylation cascade",
  "kinase enzyme",
  "phosphatase enzyme",
  "signal transduction",
  "gtp hydrolysis",
  "ras activation",
  "rap1 signaling",
  "rock kinase",
  "map kinase",
  "erk pathway",
  "p38 pathway",
  "jnk pathway",
  "pi3k pathway",
  "akt kinase",
  "mtor pathway",
  "ampk sensor",
  "sirtuin protein",
  "parp enzyme",
  "notch signaling",
  "wnt pathway",
  "hedgehog pathway",
  "bmp signaling",
  "tgf beta",
  "fgf receptor",
  "egf receptor",
  "pdgf signaling",
  "vegf angiogenesis",
  "angiopoietin",
  "endothelial cell",
  "vascular permeability",
  "tight junction",
  "adherens junction",
  "gap junction",
  "desmosome structure",
  "hemidesmosomes",
  "focal adhesion",
  "integrin receptor",
  "cadherin adhesion",
  "selectin binding",
  "immunoglobulin superfamily",
  "cell migration",
  "chemotaxis gradient",
  "haptotaxis guidance",
  "durotaxis stiffness",
  "contact inhibition",
  "epithelial mesenchymal",
  "mesenchymal epithelial",
  "pluripotency state",
  "stemness property",
  "differentiation program",
  "lineage commitment",
  "reprogramming factor",
  "induced pluripotent",
  "transdifferentiation",
  "cell dedifferentiation",
  "morphogenesis process",
  "organogenesis development",
  "embryogenesis stages",
  "gastrulation movement",
  "neurulation tube",
  "somitogenesis segmentation",
  "limb development",
  "digit formation",
  "pattern formation",
  "gradient morphogen",
  "positional information",
  "homeotic gene",
  "developmental cascade",
  "heterochrony timing",
  "neoteny juvenile",
  "progenesis early",
  "allometry scaling",
  "body plan conservation",
  "evolutionary conservation",
  "orthologous gene",
  "paralogous gene",
  "gene duplication",
  "pseudogene evolution",
  "transposable element",
  "retrotransposon",
  "dna transposon",
  "horizontal gene transfer",
  "lateral gene transfer",
  "endosymbiosis theory",
  "mitochondrial inheritance",
  "chloroplast inheritance",
  "maternal effect",
  "epigenetic inheritance",
  "dna methylation",
  "histone modification",
  "chromatin remodeling",
  "nucleosome positioning",
  "heterochromatin silencing",
  "euchromatin active",
  "x inactivation",
  "genomic imprinting",
  "paramutation",
  "gene silencing",
  "rna interference",
  "mirna regulation",
  "sirna knockdown",
  "crispr cas9",
  "prime editing",
  "base editing",
  "epigenome editing",
  "synthetic biology",
  "artificial cell",
  "protocell membrane",
  "liposome vesicle",
  "polymer replication",
  "rna world hypothesis",
  "ribozyme catalysis",
  "peptide nucleic acid",
  "xeno nucleic acid",
  "genetic code",
  "codon usage",
  "wobble pairing",
  "translation fidelity",
  "translocation step",
  "ribosome kinetics",
  "polysome cluster",
  "mrna localization",
  "protein trafficking",
  "signal peptide",
  "er retention signal",
  "golgi retrieval",
  "endosome sorting",
  "lysosome degradation",
  "proteasome efficiency",
  "membrane topology",
  "transmembrane domain",
  "protein folding",
  "misfolded protein",
  "inclusion body",
  "amyloid fibrils",
  "prion disease",
  "protein aggregation",
  "quality control system",
  "unfolded protein response",
];
