import { NextResponse, after } from "next/server";
import { revalidateTag } from "next/cache";
import { db } from "@/lib/db";
import { dithers, users, type DitherStatus } from "@/lib/db/schema";
import { uploadImage } from "@/lib/storage";
import { auth } from "@/lib/auth";
import { headers } from "next/headers";
import {
  generateTitleFromPrompt,
  generateTitleFromImage,
} from "@/lib/generate-title";
import { eq, or, desc, and, gte, sql } from "drizzle-orm";
import { generateImage } from "ai";
import { generateGeminiImageUrl } from "@/lib/gemini-image";

// Daily generation limit (default: 10)
const DAILY_GENERATION_LIMIT = parseInt(
  process.env.DAILY_GENERATION_LIMIT || "10",
  10,
);

// User IDs with unlimited generations (comma-separated)
const UNLIMITED_USER_IDS = new Set(
  (process.env.UNLIMITED_USER_IDS || "")
    .split(",")
    .map((id) => id.trim())
    .filter(Boolean),
);

async function getUserDailyGenerationCount(userId: string): Promise<number> {
  const today = new Date();
  today.setHours(0, 0, 0, 0);

  const result = await db
    .select({ count: sql<number>`count(*)` })
    .from(dithers)
    .where(and(eq(dithers.userId, userId), gte(dithers.createdAt, today)));

  return Number(result[0]?.count || 0);
}

function hasUnlimitedGenerations(userId: string): boolean {
  return UNLIMITED_USER_IDS.has(userId);
}

// Style suffix to encourage dark backgrounds and no text for better dithering
const STYLE_SUFFIX =
  ", dark background, high contrast, no text, no words, no letters, no watermarks";

// Gemini models that use a different generation method
const GEMINI_MODELS = [
  "google/gemini-2.5-flash-image",
  "google/gemini-3-pro-image",
];

async function generateAndProcessImage(
  id: string,
  prompt: string,
  modelId: string,
) {
  try {
    // Generate title first (fast) and update immediately so it shows during generation
    const titlePromise = generateTitleFromPrompt(prompt);

    // Update status to generating
    await db
      .update(dithers)
      .set({ status: "generating" as DitherStatus, updatedAt: new Date() })
      .where(eq(dithers.id, id));

    // Wait for title and update it right away
    const title = await titlePromise;
    await db
      .update(dithers)
      .set({ title, updatedAt: new Date() })
      .where(eq(dithers.id, id));

    console.log(`[${id}] Title generated: "${title}"`);

    const enhancedPrompt = prompt.trim() + STYLE_SUFFIX;
    console.log(
      `[${id}] Generating image for prompt: "${enhancedPrompt}" using model: ${modelId}`,
    );

    let imageUrl: string;

    if (GEMINI_MODELS.includes(modelId)) {
      const url = await generateGeminiImageUrl(enhancedPrompt, modelId);
      if (!url) {
        throw new Error("No image generated by Gemini");
      }
      imageUrl = url;
    } else {
      const result = await generateImage({
        model: modelId,
        prompt: enhancedPrompt,
      });

      const image = result.images[0];
      if (!image) {
        throw new Error("No image in response");
      }

      if (typeof image === "string") {
        imageUrl = image;
      } else if (image.base64) {
        imageUrl = `data:image/png;base64,${image.base64}`;
      } else if (image.uint8Array) {
        const base64 = Buffer.from(image.uint8Array).toString("base64");
        imageUrl = `data:image/png;base64,${base64}`;
      } else {
        throw new Error("Unknown image format in response");
      }
    }

    console.log(`[${id}] Image generation completed, uploading original...`);

    // Upload only the original image (dithering happens client-side)
    // The dithered version will be saved when the client first views it
    await uploadImage(imageUrl, `${id}-original.png`);

    // Update the dither record - imageUrl stays null until client saves dithered version
    await db
      .update(dithers)
      .set({
        status: "ready" as DitherStatus,
        updatedAt: new Date(),
      })
      .where(eq(dithers.id, id));

    console.log(`[${id}] Dither ready`);
  } catch (error) {
    console.error(`[${id}] Error generating image:`, error);

    // Update status to failed
    await db
      .update(dithers)
      .set({
        status: "failed" as DitherStatus,
        errorMessage:
          error instanceof Error ? error.message : "Unknown error occurred",
        updatedAt: new Date(),
      })
      .where(eq(dithers.id, id));
  }
}

export async function POST(request: Request) {
  try {
    const session = await auth.api.getSession({
      headers: await headers(),
    });

    if (!session?.user) {
      return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
    }

    const body = await request.json();

    // Check if this is a "generate" request (has prompt and modelId)
    // or a "save" request (has originalImageData and processedImageData)
    const isGenerateRequest =
      body.prompt && body.modelId && !body.originalImageData;

    if (isGenerateRequest) {
      // Create a pending dither and start background generation
      const { id, prompt, modelId, visibility = "private" } = body;

      if (!id) {
        return NextResponse.json({ error: "ID is required" }, { status: 400 });
      }

      // Check daily generation limit (unless user has unlimited)
      if (!hasUnlimitedGenerations(session.user.id)) {
        const todayCount = await getUserDailyGenerationCount(session.user.id);
        if (todayCount >= DAILY_GENERATION_LIMIT) {
          return NextResponse.json(
            {
              error: `Daily limit reached. You can generate ${DAILY_GENERATION_LIMIT} images per day.`,
              limitReached: true,
              limit: DAILY_GENERATION_LIMIT,
              used: todayCount,
            },
            { status: 429 },
          );
        }
      }

      // Create the pending dither record
      const [dither] = await db
        .insert(dithers)
        .values({
          id,
          userId: session.user.id,
          prompt,
          modelId,
          visibility,
          status: "pending",
          threshold: "255",
          contrast: "2",
          brightness: "75",
        })
        .returning();

      // Start background generation using after()
      after(async () => {
        await generateAndProcessImage(id, prompt, modelId);
        // Revalidate caches after generation completes
        revalidateTag("dithers");
        revalidateTag(`my-dithers-${session.user.id}`);
      });

      // Revalidate caches immediately for pending state
      revalidateTag("dithers");
      revalidateTag(`my-dithers-${session.user.id}`);

      return NextResponse.json({ dither });
    }

    // Legacy save request - for uploaded images
    const { id, prompt, originalImageData, processedImageData } = body;

    if (!id) {
      return NextResponse.json({ error: "ID is required" }, { status: 400 });
    }

    if (!originalImageData || !processedImageData) {
      return NextResponse.json(
        { error: "Both original and processed image data are required" },
        { status: 400 },
      );
    }

    // Upload both images to storage
    // Original: {id}-original.png, Processed: {id}.png
    const [, imageUrl] = await Promise.all([
      uploadImage(originalImageData, `${id}-original.png`),
      uploadImage(processedImageData, `${id}.png`),
    ]);

    // Generate title based on whether we have a prompt (generated) or not (uploaded)
    let title: string;
    if (prompt) {
      title = await generateTitleFromPrompt(prompt);
    } else {
      title = await generateTitleFromImage(originalImageData);
    }

    // Create the dither record (imageUrl points to processed image)
    // Use explicit default dither settings
    const [dither] = await db
      .insert(dithers)
      .values({
        id,
        userId: session.user.id,
        title,
        prompt: prompt || null,
        imageUrl,
        threshold: "255",
        contrast: "2",
        brightness: "75",
        status: "ready",
      })
      .returning();

    // Revalidate caches
    revalidateTag("dithers");
    revalidateTag(`my-dithers-${session.user.id}`);

    return NextResponse.json({ dither });
  } catch (error) {
    console.error("Error creating dither:", error);
    return NextResponse.json(
      {
        error: `Failed to create dither: ${error instanceof Error ? error.message : "Unknown error"}`,
      },
      { status: 500 },
    );
  }
}

export async function GET() {
  try {
    const session = await auth.api.getSession({
      headers: await headers(),
    });

    const userId = session?.user?.id;

    // Build where clause: public dithers OR user's own dithers (if signed in)
    const whereClause = userId
      ? or(eq(dithers.visibility, "public"), eq(dithers.userId, userId))
      : eq(dithers.visibility, "public");

    // Fetch dithers with user info
    const results = await db
      .select({
        id: dithers.id,
        title: dithers.title,
        imageUrl: dithers.imageUrl,
        visibility: dithers.visibility,
        status: dithers.status,
        createdAt: dithers.createdAt,
        userId: dithers.userId,
        userName: users.name,
        userImage: users.image,
      })
      .from(dithers)
      .leftJoin(users, eq(dithers.userId, users.id))
      .where(whereClause)
      .orderBy(desc(dithers.createdAt))
      .limit(50);

    // Separate into user's dithers and public dithers
    // Only show dithers that have been processed (have an imageUrl)
    const myDithers = userId
      ? results.filter((d) => d.userId === userId && d.imageUrl)
      : [];
    const publicDithers = results.filter(
      (d) => d.visibility === "public" && d.userId !== userId && d.imageUrl,
    );

    return NextResponse.json({
      myDithers,
      publicDithers,
    });
  } catch (error) {
    console.error("Error fetching dithers:", error);
    return NextResponse.json(
      { error: "Failed to fetch dithers" },
      { status: 500 },
    );
  }
}
