import { generateImage } from "ai";
import { NextResponse } from "next/server";
import { generateGeminiImageUrl } from "@/lib/gemini-image";

// Style suffix to encourage dark backgrounds and no text for better dithering
const STYLE_SUFFIX =
  ", dark background, high contrast, no text, no words, no letters, no watermarks";

export async function POST(request: Request) {
  try {
    const { prompt, modelId = "bfl/flux-kontext-max" } = await request.json();

    if (!prompt) {
      return NextResponse.json(
        { error: "Prompt is required" },
        { status: 400 },
      );
    }

    // Enhance prompt with style guidance for better dithering results
    const enhancedPrompt = prompt.trim() + STYLE_SUFFIX;

    console.log(
      `Generating image for prompt: "${enhancedPrompt}" using model: ${modelId}`,
    );

    let imageUrl: string;

    // Use different generation method for Gemini models (they use generateText)
    const geminiModels = [
      "google/gemini-2.5-flash-image",
      "google/gemini-3-pro-image",
    ];

    if (geminiModels.includes(modelId)) {
      const url = await generateGeminiImageUrl(enhancedPrompt, modelId);

      if (!url) {
        console.error("No image generated by Gemini");
        return NextResponse.json(
          { error: "No image found in the response" },
          { status: 500 },
        );
      }

      imageUrl = url;
    } else {
      // Generate the image using AI SDK with AI Gateway
      const result = await generateImage({
        model: modelId,
        prompt: enhancedPrompt,
      });

      console.log("Image generation completed");

      // Extract the image from the response
      const image = result.images[0];

      if (!image) {
        console.error("No image in response");
        return NextResponse.json(
          { error: "No image found in the response" },
          { status: 500 },
        );
      }

      // Convert to base64 data URL if it's a Uint8Array, or use URL if available
      if (typeof image === "string") {
        imageUrl = image;
      } else if (image.base64) {
        imageUrl = `data:image/png;base64,${image.base64}`;
      } else if (image.uint8Array) {
        const base64 = Buffer.from(image.uint8Array).toString("base64");
        imageUrl = `data:image/png;base64,${base64}`;
      } else {
        console.error("Unknown image format:", image);
        return NextResponse.json(
          { error: "Unknown image format in response" },
          { status: 500 },
        );
      }
    }

    return NextResponse.json({
      image: {
        id: `${Date.now()}`,
        url: imageUrl,
      },
    });
  } catch (error) {
    console.error("Error generating image:", error);
    return NextResponse.json(
      {
        error: `Failed to generate image: ${error instanceof Error ? error.message : "Unknown error"}`,
      },
      { status: 500 },
    );
  }
}
